query Recipes($first: Int, $after: String) {
  recipes(first: $first, after: $after) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        title
        bannerUrl
        servings
        voteAverage
        votes
        author {
          username
          name
          avatarUrl
        }
      }
    }
    nodes {
      id
      title
      bannerUrl
      servings
      voteAverage
      votes
      author {
        username
        name
        avatarUrl
      }
    }
  }
}

query Recipe($id: Int!) {
  recipe(id: $id) {
    id
    title
    bannerUrl
    servings
    voteAverage
    ingredients {
      id
      name
      unit
      quantity
    }
    indications {
      prepTime
      cookTime
      restTime
      difficulty
    }
    steps {
      stepNumber
      description
      imageUrl
    }
    author {
      name
      avatarUrl
    }
  }
}
