query Recipes($first: Int, $after: String) {
  recipes(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      title
      bannerUrl
      voteAverage
      author {
        name
      }
    }
  }
}

query Recipe($id: Int!) {
  recipe(id: $id) {
    id
    title
    bannerUrl
    servings
    voteAverage
    ingredients {
      id
      name
      unit
      quantity
    }
    indications {
      prepTime
      cookTime
      restTime
      difficulty
    }
    steps {
      stepNumber
      description
      imageUrl
    }
    author {
      name
      avatarUrl
    }
  }
}
